### ISSUE TITLE
Add screenshots

### ISSUE THREAD

**Issue by AhsanSN** [janpio/ionic-native-contacts#2]
Can you please add some screenshots?

**Comment by janpio** [comment]
Of the app? To the readme?

**Comment by AhsanSN** [comment]
yup

**Comment by janpio** [comment]
That would be quite difficult because I would have to scrub the contact data out of the screenshots unfortunately.

The UI is all this:
https://github.com/janpio/ionic-native-contacts/blob/e6d7078ee163db3897651e6356efd67af540b24e/src/pages/home/home.html#L14-L25
Two buttons, a list of contacts (Profile picture, name, number) that could be read beneath.
